apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: poad-apiserver-env.networking.gardener.cloud
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1C
    url: https://localhost:10250/webhook/pod-apiserver-env
  failurePolicy: Ignore
  matchPolicy: Exact
  name: poad-apiserver-env.networking.gardener.cloud
  namespaceSelector:
    matchExpressions:
    - key: apiserver-proxy.networking.gardener.cloud/inject
      operator: NotIn
      values:
      - "f"
      - "F"
      - "FALSE"
      - "false"
      - "False"
      - "0"
  objectSelector:
    matchExpressions:
    - key: apiserver-proxy.networking.gardener.cloud/inject
      operator: NotIn
      values:
      - "f"
      - "F"
      - "FALSE"
      - "false"
      - "False"
      - "0"
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 2
